# TONlib parameters
tonlib_config_path: /run/secrets/ton-global-config  # TON global config path 
tonlib_keystore_path: /tmp/keystore/  # TONlib keystore path
tonlib_boc_endpoints: []  # Endpoints to duplicate incoming BOCs
tonlib_threads: 4  # number of threads for TONlib multiclient

server_port: 8081   # API port in container,
                    # to change exposed port set THACPP_PORT env variable
monitor_port: 8082  # Monitoring port in container, 
                    # to change exposed port set THACPP_MONITOR_PORT env variable

main_worker_threads: 4  # number of threads to serve HTTP requests
fs_worker_threads: 1    # number of threads for I/O operations, f.e. logging
http_worker_threads: 2  # number of threads for http client 
                        # to duplicate BOCs on external service

log_level: warning          # api v2 log level
log_path: "@stdout"         # log destination, available options:
                            # @stdout
                            # @stderr
                            # @null - don't log
                            # /path/to/file - log to file
                            # Note: if you log into file,
                            # logs will be deleted after deploying new container
system_log_level: warning   # userver system logs
system_log_path: "@stdout"

jsonrpc_log_level: warning  # jsonrpc endpoint logs
                            # note that requests to jsonRPC endpoint will appear in both of api-v2 and jsonrpc loggers
jsonrpc_log_path: "@stdout"

log_format: json            # logs format, one of `tskv`, `ltsv`, `json`

http_worker_user_agent: empty  # http user agent to set in request to boc endpoint

static_content_dir: "/static/"  # directory for static content
max_stack_entry_depth: 100      # max stack entry depth for runGetMethod
